# Site settings
title: Code.to_a (tea)
header-img: img/home-bg.png
email: ashleyeschultz@gmail.com
copyright_name: ashley3schultz
description: > # this means to ignore newlines until "baseurl:"
  Enjoying The Process
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ashley3schultz
learn_profile: ashley3schultz
email_username: ashleyeschultz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
